[project]
name = "counter"
authors = []
description = ""
telemetry = false

[contracts.counter]
path = "contracts/counter.clar"
clarity = 1
epoch = "2.05"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
