[package]
name = "stacks-network"
version = "1.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
crossterm = { version = "0.22.1", optional = true }
bitcoin = "0.29.2"
bitcoincore-rpc = "0.16.0"
clap_generate = { version = "3.0.3", optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["preserve_order"] }
serde_derive = "1"
tar = "0.4.26"
tracing = "0.1"
tracing-subscriber = "0.3.3"
tracing-appender = "0.2.0"
ctrlc = "3.1.9"
reqwest = { version = "0.11", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
tui = { version = "0.18.0", default-features = false, features = [
    "crossterm",
] }
crossbeam-channel = "0.5.6"

chrono = "0.4.20"
futures = "0.3.12"
base58 = "0.2.0"

chainhook-event-observer = { version = "=1.0.6", default-features = false, features = ["log", "ordinals"], path = "../../../chainhook/components/chainhook-event-observer" }
# chainhook-event-observer = { version = "=1.0.6", default-features = false, features = ["log", "ordinals"] }
stacks-rpc-client = { version = "1.0.1" }
clarinet-files = { version = "1.0.0", features = ["cli"]  }
clarinet-deployments = { path = "../clarinet-deployments", features = ["cli"]  }
clarinet-utils = { version = "1.0.0" }
hiro-system-kit = { version = "0.1.0", features = ["log"] }
clarity-repl = { version = "1.5.0", features = ["cli"] }
dirs = { version = "4.0.0" }
clap = {version = "4.2.7", features = [ "derive" ] }
serde_yaml = "0.9.21"

[lib]
name = "stacks_network"
path = "src/lib.rs"
# Default type
# crate-type = ["lib"]
# Use this instead for WASM builds
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stacks-network"
path = "src/main.rs"

[features]
default = ["crossterm"]

